name: Rust Actix CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install libzmq
        run: sudo apt-get update && sudo apt-get install -y libzmq3-dev

      - name: Set PKG_CONFIG_PATH
        run: echo "::set-env name=PKG_CONFIG_PATH::/usr/lib/pkgconfig"

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
