name: Rust Actix CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install libzmq
        run: sudo apt-get update && sudo apt-get install -y libzmq3-dev

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Set LIBZMQ_PATH environment variable
        run: echo "export LIBZMQ_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
